### ISSUE TITLE
Launching RStudio Preview opens temporary cmd prompt

### ISSUE THREAD

**Issue by baslat** [cderv/r-bucket#18]
Hi,

Thanks for putting this together. When I launch RStudio Preview installed from, it is accompanied by a very quick opening and closing of a cmd prompt. It opens and closes so quickly I cannot see what it's actually doing though. This happens every time I create a new instance of RStudio. Ideas?

Thanks!

**Comment by baslat** [comment]
My results (also Windows 11):
```
~ $ scoop shim info rstudio-preview

Name     : rstudio-preview
Path     : C:\Users\baslat\scoop\shims\rstudio-preview.exe
Source   : rstudio-preview
Type     : Application
IsGlobal : False
IsHidden : False
```

I thought it might also be the shims, so I checked launching the target exe directly (`"C:\Users\baslat\scoop\apps\rstudio-preview\2022.02.0+443\bin\rstudio.exe"`), and this also creates the and closes the cmd prompt.

I also installed the `rstudio` scoop app from the extras bucket, which appears to be the same version RStudio, and it too creates the cmd prompt, so maybe it's an RStudio thing?

```
~ $ scoop list rstudio
Installed apps matching 'rstudio':

Name            Version       Source   Updated             Info
----            -------       ------   -------             ----
rstudio         2022.02.0-443 extras   2022-03-15 06:03:30
rstudio-preview 2022.02.0+443 r-bucket 2022-03-13 14:03:26
```

> Does Rstudio IDE opens correctly ? 

Yes, apart from the cmd prompt.

> Does it happens only with the preview ? (or any app used with Scoop ?)

Other scoop apps do not do this.

**Comment by cderv** [comment]
> so I checked launching the target exe directly ("C:\Users\baslat\scoop\apps\rstudio-preview\2022.02.0+443\bin\rstudio.exe"), and this also creates the and closes the cmd prompt.

Then it is possible that this is a rstudio thing. 

I am getting the preview from here: https://www.rstudio.com/products/rstudio/download/preview/
and dailies from https://dailies.rstudio.com/rstudio/spotted-wakerobin/desktop/windows-xcopy/

I am taking the installer less version for both. You could try download them directly and see if it happens to check that it is not scoop related.

**Comment by baslat** [comment]
I haven't checked those links yet, but I think it's related to git.

**Comment by baslat** [comment]
Ok I think I have fixed it, and it was indeed related to git. In RStudio my setting for the git execeutable was poitning to `"C:\Users\baslat\scoop\shims\git.exe"`.

Changing to `"C:\Users\baslat\scoop\apps\git\current\cmd\git.exe"` (the target of the shim) stopped the pop-ups (and restored the git pane in RStudio).

**Comment by cderv** [comment]
Oh ! That is interesting - thanks for having that documented in here. I don't think I use git with scoop so I would have find that.
