### ISSUE TITLE
Installing TinyTeX fails in tlmgr --update self

### ISSUE THREAD

**Issue by pfmoore** [cderv/r-bucket#7]
When I did `scoop install TinyTeX` I git the following:

```
Installing 'TinyTeX' (2020.11) [64bit]
TinyTeX-1-v2020.11.zip (95.2 MB) [============================================================================] 100%
Checking hash of TinyTeX-1-v2020.11.zip ... ok.
Extracting TinyTeX-1-v2020.11.zip ... done.
Running pre-install script...
Linking ~\scoop\apps\TinyTeX\current => ~\scoop\apps\TinyTeX\2020.11
Running post-install script...
--> Running tlmgr path add
--> Updating tlmgr itself
tlmgr:
Line |
   4 |  tlmgr update --self
     |  ~~~~~
     | The term 'tlmgr' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
'TinyTeX' (2020.11) was installed successfully!
Notes
-----
For full documentation, see https://yihui.org/tinytex/
```

I suspect that the command `Start-Process \"cmd.exe\" \"/c `\"$dir\\bin\\win32\\tlmgr.bat path add`\"\" -Wait -NoNewWindow` in the post-install script doesn't update the PATH in the current Powershell process, so tlmgr isn't visible.

**Comment by cderv** [comment]
🤔 I remember having issue with that but I thought I had fixed it. Will need to look into this more closely. 

Is this during an update or a new installation ?

**Comment by pfmoore** [comment]
This is a new installation, the first time I have ever installed TinyTeX.

**Comment by cderv** [comment]
Thank you - this is really important information. I'll try to fix that by using a fresh installation.

**Comment by cderv** [comment]
Thanks for your patience. This should be working as expected now.

**Comment by cderv** [comment]
This is not working yet... escaping issue with how scoop works it seems.

**Comment by cderv** [comment]
Closed by https://github.com/cderv/r-bucket/commit/d06eeceeb7e4057c56c8d59b1ebc35f78c9da216
